### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by petigura** [samuelyeewl/specmatch-emp#16]
Hey, Samuel.

Tried running the complete pipeline on my machine. Looks like it made most of the way through before choking on the detrending part. Looks like some sort of issue with the csv io.

Erik

```
[cksiso_wrkdir]$ smemp specmatch ~/Dropbox/SpecMatch-Emp/spectra/iodfitsdb/rj194.1296.fits 
Reading library from /Users/petigura/.specmatchemp/library.h5
Shifting spectrum

Shifting spectrum rj194.1296
Attempting shift to spectrum NSO, median cross-correlation peak = 1.81
Attempting shift to spectrum 123239, median cross-correlation peak = 2.27
Attempting shift to spectrum 222368, median cross-correlation peak = 1.07
Attempting shift to spectrum 216899, median cross-correlation peak = 2.94
Best reference for shifting: 216899
Shifting entire spectrum
Matching spectrum
Matching region (5000, 5100)
/Users/petigura/anaconda/lib/python2.7/site-packages/lmfit/minimizer.py:532: RuntimeWarning: divide by zero encountered in double_scalars
  result.redchi = result.chisqr / result.nfree
Matching region (5100, 5200)
Matching region (5200, 5300)
Matching region (5300, 5400)
Matching region (5400, 5500)
Matching region (5500, 5600)
Matching region (5600, 5700)
Matching region (5700, 5800)
Matching region (5800, 5900)
Creating linear combinations
Linear combinations in region (5000, 5100)
/Users/petigura/anaconda/lib/python2.7/site-packages/SpecMatch_Emp-0.2-py2.7.egg/specmatchemp/match.py:379: RuntimeWarning: divide by zero encountered in divide
/Users/petigura/anaconda/lib/python2.7/site-packages/lmfit/minimizer.py:533: RuntimeWarning: invalid value encountered in log
  _log_likelihood = result.ndata * np.log(result.redchi)
Linear combinations in region (5100, 5200)
Linear combinations in region (5200, 5300)
Linear combinations in region (5300, 5400)
Linear combinations in region (5400, 5500)
Linear combinations in region (5500, 5600)
/Users/petigura/anaconda/lib/python2.7/site-packages/SpecMatch_Emp-0.2-py2.7.egg/specmatchemp/match.py:379: RuntimeWarning: invalid value encountered in divide
Linear combinations in region (5600, 5700)
Linear combinations in region (5700, 5800)
Linear combinations in region (5800, 5900)
Traceback (most recent call last):
  File "/Users/petigura/anaconda/bin/smemp", line 11, in <module>
    load_entry_point('SpecMatch-Emp==0.2', 'console_scripts', 'smemp')()
  File "build/bdist.macosx-10.6-x86_64/egg/specmatchemp/cli.py", line 122, in main
  File "build/bdist.macosx-10.6-x86_64/egg/specmatchemp/cli.py", line 17, in specmatch_spectrum
  File "build/bdist.macosx-10.6-x86_64/egg/specmatchemp/core.py", line 60, in specmatch_spectrum
  File "build/bdist.macosx-10.6-x86_64/egg/specmatchemp/specmatch.py", line 334, in lincomb
  File "build/bdist.macosx-10.6-x86_64/egg/specmatchemp/detrend.py", line 45, in __init__
  File "/Users/petigura/anaconda/lib/python2.7/csv.py", line 397, in has_header
    rdr = reader(StringIO(sample), self.sniff(sample))
  File "/Users/petigura/anaconda/lib/python2.7/csv.py", line 188, in sniff
    raise Error, "Could not determine delimiter"
_csv.Error: Could not determine delimiter
[cksiso_wrkdir]$ ls
```

**Comment by petigura** [comment]
Resolved. Closing.
