### ISSUE TITLE
Latest commit to shift.py "breaks" spectral shifting

### ISSUE THREAD

**Issue by mikelum** [samuelyeewl/specmatch-emp#18]
Sorry Samuel, I swear I'm not breaking things intentionally! ;)
With the latest commit to shift.py, for certain spectra, my test suite crashes with a ValueError (see below). If I roll back to the prior version, the same spectrum matches and shifts fine:

Possibly an off-by-one error?

--Mike

```
Traceback (most recent call last):
  File "testSpecmatch.py", line 177, in <module>
    testSpecMatch(testSpectra[2])
  File "testSpecmatch.py", line 140, in testSpecMatch
    myMatches.shift()
  File "build/bdist.linux-x86_64/egg/specmatchemp/specmatch.py", line 140, in shift
  File "build/bdist.linux-x86_64/egg/specmatchemp/shift.py", line 83, in bootstrap_shift
  File "build/bdist.linux-x86_64/egg/specmatchemp/shift.py", line 260, in shift
  File "/home/mikelum/Tools/Astro/anaconda2/lib/python2.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 775, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.

```

**Comment by samuelyeewl** [comment]
Hi Mike,

Could you send me one of the spectra that breaks the shifting code? If anything the new commit should have fixed problems with spectra of different size.

**Comment by mikelum** [comment]
I'm away from my desk for the day, but I'll commit my test code and spectra to my fork first thing tomorrow.

--Mike

**Comment by mikelum** [comment]
I pushed my test code and spectra up to my fork. Feel free to grab and test it. I think a couple of the spectra, including the Solar spectra, will work, while a couple will cause the issue (Procyon, I think).
If you run the testSpecmatch.py script (you might have to change the WL range on lines 53-54), and alter the index of the spectra on line 177 (0-5), you can run through the different spectra.
The low(-er) metallicity ([Fe/H]=-0.88) star (index=0) and the high Teff (9600K, index=5) star are...challenging, for other reasons. ;)

**Comment by mikelum** [comment]
This issue is no longer reproduce-able with the latest fixes for the <nan> issue.

**Comment by mikelum** [comment]
With the latest changes, all my test spectra now fail during the shift call.

**Comment by samuelyeewl** [comment]
Hi Mike,

I'm looking for your spectra in the fork, but I can't find it? Which branch/directory are they in?

**Comment by mikelum** [comment]
Oops, I'll put them back in.

**Comment by mikelum** [comment]
(I also thought I cancelled posting the "fail" comment, in time, but I see not...)
My spectra are re-posted in my fork, however, they all are working well. The failure I was seeing was due to  a discrepancy in the ranges:
This code works:
```
mySpectrum = fullSpectrum.cut(rangeMin-10, rangeMax+10)
    lib = specmatchemp.library.read_hdf(wavlim=[rangeMin-10, rangeMax+10])

    myMatches = SpecMatch(mySpectrum, lib=lib, wavlim=(rangeMin-10, rangeMax+10))
    
    myMatches.shift()
```
Changing the first line to:
`    mySpectrum = fullSpectrum.cut(rangeMin-20, rangeMax+20)`
...causes it to fail with:
```
Attempting shift to spectrum NSO, median cross-correlation peak = 1.53
Traceback (most recent call last):
  File "testSpecmatch.py", line 208, in <module>
    testSpecMatch(testSpectra[index])
  File "testSpecmatch.py", line 154, in testSpecMatch
    myMatches.shift()
  File "build/bdist.linux-x86_64/egg/specmatchemp/specmatch.py", line 144, in shift
  File "build/bdist.linux-x86_64/egg/specmatchemp/shift.py", line 56, in bootstrap_shift
  File "build/bdist.linux-x86_64/egg/specmatchemp/shift.py", line 260, in shift
  File "/home/mikelum/Tools/Astro/anaconda2/lib/python2.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 775, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
```

However, I'm not quite ready to post an issue yet, as I haven't verified that the " fullSpectrum.cut" call is actually trimming the spectra to valid data (ie: not sure that the passed spectrum covers that full range)

**Comment by mikelum** [comment]
Still getting 'nan' errors (is my choice of spectral range an issue?):

```
Creating linear combinations
Linear combinations in region (6308.3500000000004, 6312.9571072727404)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-d0da45de34c2> in <module>()
      1 for sd in tsm.ngc752Spectra[14:]:
----> 2     tsm.testSpecMatch(sd)
      3 

/home/mikelum/Dropbox/CodeCloud/specmatch-emp/tests/testSpecmatch.py in testSpecMatch(specFileData)
    249 
    250     # Generate best-fit parms
--> 251     myMatches.lincomb()
    252 
    253     print('Derived Parameters: ')

/home/mikelum/Tools/Astro/anaconda2/envs/astroconda/lib/python2.7/site-packages/SpecMatch_Emp-0.2-py2.7.egg/specmatchemp/specmatch.pyc in lincomb(self, num_best, regions)
    310                                             spec_refs, vsini,
    311                                             ref_chisq=ref_chisq)
--> 312             mt_lincomb.best_fit()
    313             coeffs = np.array(mt_lincomb.get_lincomb_coeffs())
    314 

/home/mikelum/Tools/Astro/anaconda2/envs/astroconda/lib/python2.7/site-packages/SpecMatch_Emp-0.2-py2.7.egg/specmatchemp/match.pyc in best_fit(self)
    424 
    425         # Minimize chi-squared
--> 426         out = lmfit.minimize(self.objective, params, method='nelder')
    427 
    428         # Save best fit parameters

...(more traces through the lmfit package

/home/mikelum/Tools/Astro/anaconda2/envs/astroconda/lib/python2.7/site-packages/lmfit-0.9.5-py2.7.egg/lmfit/minimizer.pyc in _nan_policy(a, nan_policy, handle_inf)
   1430 
   1431         if contains_nan:
-> 1432             raise ValueError("The input contains nan values")
   1433         return a
   1434 

ValueError: The input contains nan values
```

**Comment by samuelyeewl** [comment]
Hi Mike,

Yeah, that looks to be the issue - the library right now only covers 4990 - 6300 A, so your cut is just outside that. I've been working on extending the library with the data from the other chips, but for now you'll have to be limit to that range.
