### ISSUE TITLE
wrap around issue with matching code

### ISSUE THREAD

**Issue by petigura** [samuelyeewl/specmatch-emp#31]
SpecMatch seems to be trying to fit regions of spectrum that don't exist.

```
-bash-4.2$ smemp specmatch -d /mir3/iodfitsdb/rj76.279.fits 
Reading library from /home/petigura/.specmatchemp/library.h5
Reading library from /home/petigura/.specmatchemp/library.h5
Shifting spectrum
Shifting spectrum rj76.279
Attempting shift to spectrum NSO, median cross-correlation peak = 2.56
Best reference for shifting: NSO
Shifting entire spectrum
Matching spectrum
Matching region (5000, 5077.0543238899554)
Matching region (5077.0543238899554, 5177.0543238899554)
Matching region (5177.0543238899554, 5277.0543238899554)
Matching region (5277.0543238899554, 5377.0543238899554)
Matching region (5377.0543238899554, 5477.0543238899554)
Matching region (5477.0543238899554, 5577.0543238899554)
Matching region (5577.0543238899554, 5677.0543238899554)
Matching region (5677.0543238899554, 5777.0543238899554)
Matching region (5777.0543238899554, 5877.0543238899554)
Matching region (5877.0543238899554, 5977.0543238899554)
Matching region (5977.0543238899554, 6077.0543238899554)
Matching region (6077.0543238899554, 6177.0543238899554)
Matching region (6177.0543238899554, 6277.0543238899554)
Matching region (6277.0543238899554, 6377.0543238899554)
Matching region (6377.0543238899554, 5900)
Traceback (most recent call last):
  File "/data/user/petigura/code/anaconda2/bin/smemp", line 11, in <module>
    sys.exit(main())
  File "/data/user/petigura/code/anaconda2/lib/python2.7/site-packages/specmatchemp/cli.py", line 147, in main
    args.func(args)
  File "/data/user/petigura/code/anaconda2/lib/python2.7/site-packages/specmatchemp/cli.py", line 31, in specmatch_spectrum
    suffix=args.suffix, lib_subset=lib_subset)
  File "/data/user/petigura/code/anaconda2/lib/python2.7/site-packages/specmatchemp/core.py", line 72, in specmatch_spectrum
    sm.match(wavlim=wavlim)
  File "/data/user/petigura/code/anaconda2/lib/python2.7/site-packages/specmatchemp/specmatch.py", line 239, in match
    mt = match.Match(spec_targ, spec_ref.cut(*reg))
  File "/data/user/petigura/code/anaconda2/lib/python2.7/site-packages/specmatchemp/match.py", line 73, in __init__
    self.knot_x.append(self.w[interval*i])
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by samuelyeewl** [comment]
Fixed this with 17e234
